console.log("sundaram") 
console.log("Prince")
console.log("Sundaram Prince")
console.log("Shivam")
console.log("Shivam Ranjan")
console.log("Shivam Ranjan Kumar")
console.log("Shivam Ranjan Kumar Yadav")
console.log("Shivam Ranjan Kumar Yadav 1")
console.log("Shivam Ranjan Kumar Yadav 2")
console.log("Shivam Ranjan Kumar Yadav 3")
console.log("Shivam Ranjan Kumar Yadav 4")
console.log("Shivam Ranjan Kumar Yadav 5")
console.log("Shivam Ranjan Kumar Yadav 6")
console.log("Shivam Ranjan Kumar Yadav 7")
console.log("Shivam Ranjan Kumar Yadav 8")
console.log("Shivam Ranjan Kumar Yadav 9")